#!/usr/bin/env node
// E2E runner — plain Node. Spawns one Electron process per scenario file
// (tests/e2e/scenarios/*.e2e.js), parses the E2E_RESULT: line, aggregates.
//
// Usage:
//   npm run test:e2e             # all scenarios
//   npm run test:e2e layout      # scenarios whose filename contains "layout"

const { spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..', '..');
const scenariosDir = path.join(__dirname, 'scenarios');
const electronBin = path.join(root, 'node_modules', '.bin', process.platform === 'win32' ? 'electron.cmd' : 'electron');
const entryShim = path.join(root, '.e2e-entry.js');
const SCENARIO_TIMEOUT_MS = 90000;

const filter = process.argv[2] || '';
const scenarios = fs.readdirSync(scenariosDir)
    .filter(f => f.endsWith('.e2e.js'))
    .filter(f => f.includes(filter))
    .sort();

if (scenarios.length === 0) {
    console.error(`Keine Szenarien gefunden (Filter: "${filter}")`);
    process.exit(2);
}

// Entry shim in the project root so app.getAppPath() → root (see launcher.js)
fs.writeFileSync(entryShim,
    "// auto-generated by tests/e2e/run.js — do not edit, do not commit\n" +
    "require('./tests/e2e/launcher.js');\n");

let totalPassed = 0, totalFailed = 0, fatals = 0;
const summary = [];

try {
    for (const file of scenarios) {
        const scenarioPath = path.join(scenariosDir, file);
        const started = Date.now();
        const res = spawnSync(electronBin, [entryShim, scenarioPath], {
            cwd: root,
            timeout: SCENARIO_TIMEOUT_MS,
            encoding: 'utf-8',
            env: { ...process.env, E2E: '1' }
        });
        const out = (res.stdout || '') + (res.stderr || '');
        const line = out.split('\n').find(l => l.includes('E2E_RESULT:'));
        let result = null;
        if (line) {
            try { result = JSON.parse(line.slice(line.indexOf('E2E_RESULT:') + 'E2E_RESULT:'.length)); } catch (e) { /* fall through */ }
        }
        const secs = ((Date.now() - started) / 1000).toFixed(1);
        if (!result) {
            fatals++;
            summary.push(`✗ ${file} — kein Ergebnis (Timeout/Crash nach ${secs}s)`);
            console.log(`✗ ${file} — kein E2E_RESULT (Timeout/Crash). Letzte Ausgabe:\n${out.split('\n').slice(-15).join('\n')}`);
            continue;
        }
        totalPassed += result.passed;
        totalFailed += result.failed;
        if (result.fatal) {
            fatals++;
            summary.push(`✗ ${file} — FATAL: ${String(result.fatal).split('\n')[0]}`);
            console.log(`✗ ${file} (${secs}s) FATAL:\n${result.fatal}`);
        } else if (result.failed > 0) {
            summary.push(`✗ ${file} — ${result.failed} von ${result.passed + result.failed} Checks rot`);
            console.log(`✗ ${file} (${secs}s): ${result.failed} Fehler`);
            for (const f of result.failures) {
                console.log(`    ✗ ${f.name}${f.detail ? ' — ' + JSON.stringify(f.detail) : ''}`);
            }
        } else {
            summary.push(`✓ ${file} — ${result.passed} Checks`);
            console.log(`✓ ${file} (${secs}s): ${result.passed} Checks grün`);
        }
    }
} finally {
    try { fs.unlinkSync(entryShim); } catch (e) { /* ignore */ }
}

console.log('\n──────── E2E-Zusammenfassung ────────');
summary.forEach(s => console.log(s));
console.log(`Checks: ${totalPassed} grün, ${totalFailed} rot, ${fatals} fatal`);
process.exit(totalFailed > 0 || fatals > 0 ? 1 : 0);
